#!/bin/bash
# We need to do this so that the glade file can be loaded from a relative path; is there a better way?
HERE="$(dirname "$(readlink -f "${0}")")"
cd "${HERE}/usr/"
exec "${HERE}/usr/bin/netactview" "$@"
